In [16]:
import pandas as pd
import seaborn as sns

df = pd.read_csv("2026_data.csv")
print(f"Table has {df.shape[0]} rows and {df.shape[1]} columns.\n")
df.head()

Table has 13 rows and 4 columns.

        Name  VC_Grade  Initial_Stud  Final_Stud
0  Teacher 1       100            15           2
1  Teacher 2        92            11           9
2  Teacher 3        89            11           9
3  Teacher 4        85            11           5
4  Teacher 5        98             8           4

In [3]:
df.describe().round(2)

       VC_Grade  Initial_Stud  Final_Stud
count     13.00         13.00       13.00
mean      91.15         11.00        5.46
std        7.26          1.58        2.82
min       75.00          8.00        2.00
25%       86.00         10.00        3.00
50%       92.00         11.00        5.00
75%       97.00         11.00        9.00
max      100.00         15.00        9.00

In [18]:
%matplotlib inline
import matplotlib.pyplot as plt


x_axis = df.iloc[:, 2]
y_axis = df.iloc[:, 3]

labels = df.iloc[:, 0]

import plotly.express as px

fig = px.scatter(df,
                 x=df.columns[2],
                 y=df.columns[3],
                 hover_name=df.columns[0])
fig.show()